import React, { useState, useEffect } from 'react';
import api from '@/utils/api';
import { Sparkles, RefreshCcw, RotateCw, CheckCircle2, ChevronLeft, ChevronRight, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';

const FlashcardPlayer = ({ courseId, lectureId, lectureTitle, lectureDescription }) => {
    const [cards, setCards] = useState([]);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isFlipped, setIsFlipped] = useState(false);
    const [loading, setLoading] = useState(false);
    const [regenerating, setRegenerating] = useState(false);

    const fetchCards = async () => {
        setLoading(true);
        try {
            const { data } = await api.post('/ai/flashcards', {
                courseId, 
                lectureId, 
                lectureTitle, 
                content: lectureDescription || `Lesson: ${lectureTitle}`
            });
            if (data.success) {
                const fetched = data.data?.cards || data.cards || [];
                setCards(fetched);
                setCurrentIndex(0);
                setIsFlipped(false);
            }
        } catch (error) {
            console.error('Flashcard sync failure:', error);
        } finally {
            setLoading(false);
        }
    };

    const handleRegenerate = async () => {
        setRegenerating(true);
        try {
            // Delete existing cards for this lecture, then regenerate
            await api.delete(`/ai/flashcards/${courseId}/${lectureId}`).catch(() => {});
            await fetchCards();
        } finally {
            setRegenerating(false);
        }
    };

    useEffect(() => {
        if (courseId && lectureId) {
            fetchCards();
        }
    }, [courseId, lectureId]);

    const handleNext = () => {
        setIsFlipped(false);
        setTimeout(() => {
            setCurrentIndex((prev) => (prev + 1) % cards.length);
        }, 150);
    };

    const handlePrev = () => {
        setIsFlipped(false);
        setTimeout(() => {
            setCurrentIndex((prev) => (prev - 1 + cards.length) % cards.length);
        }, 150);
    };

    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center p-20 bg-white/5 rounded-[2rem] border border-white/10">
                <Loader2 className="text-emerald-500 animate-spin mb-4" size={32} />
                <p className="text-[10px] font-black text-gray-500 uppercase tracking-[0.4em]">Synthesizing knowledge cards...</p>
            </div>
        );
    }

    if (cards.length === 0) {
        return (
            <div className="flex flex-col items-center justify-center p-20 bg-white/5 rounded-[2rem] border border-white/10 text-center">
                <Sparkles className="text-emerald-500/20 mb-4" size={48} />
                <p className="text-gray-400 text-[11px] font-black uppercase tracking-widest max-w-xs">AI is ready to generate active recall assets for this lesson.</p>
                <button 
                    onClick={fetchCards}
                    className="mt-8 px-8 py-3 bg-emerald-600 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-500 transition-all"
                >
                    Generate Flashcards
                </button>
            </div>
        );
    }

    const currentCard = cards[currentIndex];

    return (
        <div className="space-y-8">
            <div className="flex items-center justify-between px-2">
                <div>
                    <h3 className="text-sm font-black text-white uppercase tracking-tighter flex items-center gap-2">
                        <Sparkles size={14} className="text-emerald-400" />
                        Active Recall Session
                    </h3>
                    <p className="text-[9px] font-bold text-gray-500 uppercase tracking-widest mt-1">Generated by PrismAI</p>
                </div>
                <div className="flex items-center gap-3">
                    <button
                        onClick={handleRegenerate}
                        disabled={regenerating}
                        className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-gray-400 hover:text-emerald-400 px-3 py-1.5 rounded-lg text-[9px] font-black uppercase tracking-widest transition-all disabled:opacity-50"
                        title="Regenerate flashcards"
                    >
                        <RefreshCcw size={12} className={regenerating ? 'animate-spin' : ''} />
                        {regenerating ? 'Regenerating...' : 'Refresh'}
                    </button>
                    <div className="bg-emerald-500/10 text-emerald-400 px-3 py-1.5 rounded-lg text-[10px] font-black tracking-widest border border-emerald-500/20">
                        {currentIndex + 1} / {cards.length}
                    </div>
                </div>
            </div>

            {/* Flashcard Base */}
            <div 
                className="perspective-1000 relative w-full h-80 cursor-pointer group"
                onClick={() => setIsFlipped(!isFlipped)}
            >
                <motion.div 
                    initial={false}
                    animate={{ rotateY: isFlipped ? 180 : 0 }}
                    transition={{ type: 'spring', stiffness: 260, damping: 20 }}
                    className="relative w-full h-full preserve-3d"
                >
                    {/* Front */}
                    <div className="absolute w-full h-full backface-hidden bg-slate-900 border border-white/10 rounded-[2.5rem] p-10 flex flex-col items-center justify-center text-center shadow-2xl">
                        <div className="absolute top-8 left-10 flex items-center gap-2 opacity-30">
                            <RefreshCcw size={12} className="text-emerald-400" />
                            <span className="text-[8px] font-black uppercase tracking-widest">Question</span>
                        </div>
                        <h4 className="text-xl md:text-2xl font-black text-white leading-tight tracking-tight">
                            {currentCard.question}
                        </h4>
                        <div className="absolute bottom-8 text-[9px] font-black text-gray-500 uppercase tracking-[0.3em] group-hover:text-emerald-400 transition-colors animate-pulse">
                            Click to reveal answer
                        </div>
                    </div>

                    {/* Back */}
                    <div className="absolute w-full h-full backface-hidden bg-emerald-950 border border-emerald-500/30 rounded-[2.5rem] p-10 flex flex-col items-center justify-center text-center shadow-2xl overflow-y-auto" style={{ transform: 'rotateY(180deg)' }}>
                         <div className="absolute top-8 left-10 flex items-center gap-2 opacity-50">
                            <CheckCircle2 size={12} className="text-emerald-400" />
                            <span className="text-[8px] font-black uppercase tracking-widest text-emerald-400">Verified Answer</span>
                        </div>
                        <p className="text-lg font-bold text-emerald-100 leading-relaxed">
                            {currentCard.answer}
                        </p>
                        <div className="absolute bottom-8 text-[9px] font-black text-emerald-400/50 uppercase tracking-[0.3em]">
                            Click to flip back
                        </div>
                    </div>
                </motion.div>
            </div>

            {/* Card Dots Indicator */}
            <div className="flex items-center justify-center gap-2">
                {cards.map((_, i) => (
                    <button
                        key={i}
                        onClick={() => { setIsFlipped(false); setTimeout(() => setCurrentIndex(i), 100); }}
                        className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${
                            i === currentIndex 
                                ? 'bg-emerald-500 scale-125 shadow-lg shadow-emerald-500/50' 
                                : 'bg-white/10 hover:bg-white/20'
                        }`}
                        title={`Card ${i + 1}`}
                    />
                ))}
            </div>

            {/* Controls */}
            <div className="flex items-center justify-center gap-6">
                <button 
                    onClick={(e) => { e.stopPropagation(); handlePrev(); }}
                    className="w-12 h-12 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl flex items-center justify-center text-white transition-all active:scale-90"
                >
                    <ChevronLeft size={20} />
                </button>
                <button 
                    onClick={(e) => { e.stopPropagation(); setIsFlipped(!isFlipped); }}
                    className="h-12 px-8 bg-emerald-600 hover:bg-emerald-500 text-white rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] shadow-xl shadow-emerald-900/30 transition-all flex items-center gap-3 active:scale-95"
                >
                    <RotateCw size={14} className={isFlipped ? 'rotate-180 transition-transform' : ''} />
                    Flip Card
                </button>
                <button 
                    onClick={(e) => { e.stopPropagation(); handleNext(); }}
                    className="w-12 h-12 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl flex items-center justify-center text-white transition-all active:scale-90"
                >
                    <ChevronRight size={20} />
                </button>
            </div>

            {/* Spaced Repetition Logic Teaser */}
            <div className="bg-white/5 border border-white/10 rounded-2xl p-4 flex items-center justify-between">
                <p className="text-[10px] font-black text-gray-500 uppercase tracking-widest">Mastery Level</p>
                <div className="flex gap-1.5">
                    {[1, 2, 3, 4, 5].map(i => (
                        <div key={i} className={`w-2 h-2 rounded-full ${i <= 2 ? 'bg-emerald-500' : 'bg-white/10'}`} />
                    ))}
                </div>
            </div>
        </div>
    );
};

export default FlashcardPlayer;
